set compatible=off
set hidden
set mouse=a
set confirm
set timeout=off
set ttimeout
set ttimeoutlen=200
set wildmenu
set showcmd
set hlsearch
set incsearch
set showmatch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set smarttab
set startofline=off
set ruler
set virtualedit=onemore
set errorbells=off
set visualbell
set cmdheight=2
set number
set laststatus=2
set pastetoggle=<f2>
